# Generated by Django 4.2.7 on 2024-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_location_address_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_via_sms',
            field=models.BooleanField(default=False),
        ),
    ]
