# Generated by Django 4.2.7 on 2024-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_fcm_token_customuser_notify_via_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notify_via_sms',
            field=models.BooleanField(default=True),
        ),
    ]
