name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_REPOSITORY: mbishu2002/resilix-rest
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: resilixdev  

    permissions:
      contents: read  
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.AUTH_TOKEN }}

      - name: Build, tag, and push image to GitHub Container Registry
        id: build-image
        run: |
          docker build \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg ACCOUNT_SID=${{ secrets.ACCOUNT_SID }} \
            --build-arg TWILLO_AUTH_TOKEN=${{ secrets.TWILLO_AUTH_TOKEN }} \
            --build-arg COUNTRY_CODE=${{ secrets.COUNTRY_CODE }} \
            --build-arg TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }} \
            --build-arg FCM_SERVER_KEY=${{ secrets.FCM_SERVER_KEY }} \
            -t ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "::set-output name=image::${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
        env:
          DOCKER_BUILDKIT: 1
